# Generated by Django 5.2.4 on 2025-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(default='Unknown Bus', max_length=100),
        ),
    ]
