# Generated by Django 5.2.4 on 2025-07-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_cancelled_alter_bus_name_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seats_layout',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
