# Generated by Django 5.2.4 on 2025-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bus_seats_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seats_layout',
            field=models.CharField(default='2x2', max_length=10),
        ),
    ]
